#!/usr/bin/env python3
"""Train CSRNet on ShanghaiTech density maps generated by prepare script."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.models import VGG16_Weights, vgg16

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))
torch.hub.set_dir(str(BACKEND_DIR / "models" / "torch_cache"))

from app.services.vision.drone_crowd_counting import CSRNet, _extract_state_dict


class CrowdDataset(Dataset):
    def __init__(self, image_paths: list[str], train: bool):
        self.image_paths = image_paths * 4 if train else image_paths
        self.train = train
        self.transform = transforms.Compose(
            [
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            ]
        )

    def __len__(self) -> int:
        return len(self.image_paths)

    def __getitem__(self, index: int):
        import h5py
        from PIL import Image

        image_path = Path(self.image_paths[index])
        gt_dir = image_path.parent.parent / "ground_truth"
        gt_path = gt_dir / image_path.with_suffix(".h5").name
        if not gt_path.exists():
            gt_path = gt_dir / f"GT_{image_path.with_suffix('.h5').name}"

        with Image.open(image_path) as image:
            image = image.convert("RGB")

        with h5py.File(gt_path, "r") as h5_file:
            target = np.asarray(h5_file["density"], dtype=np.float32)

        target = cv2.resize(
            target,
            (target.shape[1] // 8, target.shape[0] // 8),
            interpolation=cv2.INTER_CUBIC,
        ) * 64

        return self.transform(image), torch.from_numpy(target).unsqueeze(0)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train CSRNet for ShanghaiTech crowd counting")
    parser.add_argument("--train-json", type=Path, required=True)
    parser.add_argument("--val-json", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("backend/models/csrnet_shanghaitech.pth"))
    parser.add_argument("--resume", type=Path)
    parser.add_argument("--epochs", type=int, default=400)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-7)
    parser.add_argument("--no-vgg-pretrained", action="store_true")
    parser.add_argument("--max-train-batches", type=int, help="Limit training batches per epoch for smoke tests")
    parser.add_argument("--max-val-batches", type=int, help="Limit validation batches per epoch for smoke tests")
    return parser.parse_args()


def load_json(path: Path) -> list[str]:
    return json.loads(path.read_text())


def initialize_frontend(model: CSRNet, use_pretrained: bool) -> None:
    if not use_pretrained:
        return

    weights = VGG16_Weights.IMAGENET1K_V1
    vgg = vgg16(weights=weights).features[:23]
    model.frontend.load_state_dict(vgg.state_dict())


def load_checkpoint(path: Path, model: CSRNet, optimizer: torch.optim.Optimizer, device: torch.device) -> int:
    checkpoint = torch.load(path, map_location=device, weights_only=False)
    model.load_state_dict(_extract_state_dict(checkpoint))
    if isinstance(checkpoint, dict) and "optimizer" in checkpoint:
        optimizer.load_state_dict(checkpoint["optimizer"])
    return int(checkpoint.get("epoch", 0)) if isinstance(checkpoint, dict) else 0


def validate(model: CSRNet, loader: DataLoader, device: torch.device, max_batches: int | None = None) -> float:
    model.eval()
    mae = 0.0
    batches = 0

    with torch.no_grad():
        for batches, (image, target) in enumerate(loader, start=1):
            image = image.to(device)
            target = target.to(device)
            output = model(image)
            mae += abs(output.sum() - target.sum()).item()
            if max_batches is not None and batches >= max_batches:
                break

    return mae / max(1, batches)


def main() -> None:
    args = parse_args()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = CSRNet().to(device)
    initialize_frontend(model, not args.no_vgg_pretrained)

    criterion = nn.MSELoss(reduction="sum").to(device)
    optimizer = torch.optim.SGD(model.parameters(), args.lr, momentum=0.95, weight_decay=5e-4)
    start_epoch = load_checkpoint(args.resume, model, optimizer, device) if args.resume else 0

    train_loader = DataLoader(
        CrowdDataset(load_json(args.train_json), train=True),
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.workers,
    )
    val_loader = DataLoader(
        CrowdDataset(load_json(args.val_json), train=False),
        batch_size=1,
        shuffle=False,
        num_workers=args.workers,
    )

    best_mae = float("inf")
    args.output.parent.mkdir(parents=True, exist_ok=True)

    for epoch in range(start_epoch, args.epochs):
        model.train()
        running_loss = 0.0

        train_batches = 0
        for train_batches, (image, target) in enumerate(train_loader, start=1):
            image = image.to(device)
            target = target.to(device)

            optimizer.zero_grad()
            loss = criterion(model(image), target)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            if args.max_train_batches is not None and train_batches >= args.max_train_batches:
                break

        mae = validate(model, val_loader, device, args.max_val_batches)
        checkpoint = {
            "epoch": epoch + 1,
            "state_dict": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "best_mae": min(best_mae, mae),
        }
        torch.save(checkpoint, args.output.with_suffix(".checkpoint.pth"))

        if mae < best_mae:
            best_mae = mae
            torch.save(model.state_dict(), args.output)

        print(
            f"epoch={epoch + 1} loss={running_loss / max(1, train_batches):.4f} "
            f"mae={mae:.3f} best_mae={best_mae:.3f}"
        )


if __name__ == "__main__":
    main()
